# ###############################################
# Copyright 2011-2019 EUDAT CDI - www.eudat.eu
# ###############################################

project:
  title: SeaDataCloud HTTP-API
  description: Processing data in SeaDataCloud project
  version: "1.2.1"
  rapydo: "2.1"

tags:
  seadatacloud: endpoints related to the SeaDataCloud project
  ingestion: submission of files to be approved into the cloud
  order: request an order from the interface
  # eudat: all endpoints associated to EUDAT services
  # b2safe: proxy access to irods b2safe credentials
  # registered: upload, download, list and delete objects
  # pids: resolve and download data from EUDAT Persistent IDentifier
  # publish: allow public access to data objects
  # public: landing page

variables:
  env:
    SEADATA_API_VERSION: 1.2.1.0001

    LOG_LEVEL: INFO
    AUTH_SERVICE: sqlalchemy
    CELERY_BACKEND: REDIS
    CELERY_ENABLE_CONNECTOR: 1
    ACTIVATE_RABBIT: 1
    ACTIVATE_REDIS: 1
    ACTIVATE_FLOWER: 1

    # 72 hours
    TOKEN_LONG_TTL: 259200
    TOKEN_SHORT_TTL: 259200
    ALLOW_ACCESS_TOKEN_PARAMETER: 1

    ###############################
    ACTIVATE_ICAT: 0
    IRODS_ENABLE_CONNECTOR: 1
    IRODS_USER: irods
    IRODS_PASSWORD: "**PLACEHOLDER**"
    IRODS_ZONE: tempZone
    IRODS_HOME: home
    IRODS_AUTHSCHEME: credentials
    IRODS_HOST: rodserver.dockerized.io
    IRODS_PORT: 1247
    IRODS_DB: ICAT
    IRODS_EXPIRATION_TIME: 7200
    IRODS_VERIFICATION_TIME: 900
    # anonymous user is used to download the orders via iticket
    IRODS_ANONYMOUS: 1

    ###############################
    ACTIVATE_POSTGRES: 1
    ALCHEMY_USER: rods
    ALCHEMY_DBS: "SQL_API ICAT"
    ###############################

    SEADATA_EDMO_CODE: "**PLACEHOLDER**"
    # The names of the directories in the irods zone
    # for pre-production batches, for production batches,
    # and for orders being prepared.
    SEADATA_INGESTION_COLL: batches # on irods
    SEADATA_ORDERS_COLL: orders # on irods
    SEADATA_PRODUCTION_COLL: cloud # on irods
    SEADATA_PRIVILEGED_USERS: # command separated list of privileges users

    SEADATA_WORKSPACE_INGESTION: batches # on filesystem (to be mounted to celery workers and rancher containers)
    SEADATA_WORKSPACE_ORDERS: orders # on filesystem (to be mounted to celery workers and rancher containers)
    SEADATA_API_IM_URL: https://importmanager.seadatanet.org/api_v1
    # This is the mount point of $RESOURCES_LOCALPATH inside the containers
    # Note that this variable has only effect in backend and celery containers
    # while QC containers uses an hard-code mount point (/usr/share)
    SEADATA_RESOURCES_MOUNTPOINT: /usr/share

    ## RANCHER
    RESOURCES_URL: https://cattle.yourdomain.com/v2-beta
    RESOURCES_QCLABEL: qc
    RESOURCES_KEY:
    RESOURCES_SECRET:
    RESOURCES_PROJECT:
    ## PRIVATE DOCKERHUB
    RESOURCES_HUB:
    RESOURCES_HUBUSER:
    RESOURCES_HUBPASS:
    CONTAINERS_WAIT_STOPPED: 0
    CONTAINERS_WAIT_RUNNING: 0
    # This path is the host directory that is bind-mounted
    # into the Rancher containers and into the Celery
    # worker containers. (Has to be the same, as they
    # exchange data).
    # This path needs permissions to user 1001
    # as owner of subdir 'ingestion' and 'cloud'
    RESOURCES_LOCALPATH: /nfs/share

    ## RABBIT SEADATA
    ACTIVATE_LOGGING_RABBIT: 0
    RABBIT_HOST: rabbit.b2host.org
    RABBIT_PORT: 5672
    RABBIT_VHOST: elkstack
    RABBIT_USER: elkuser
    RABBIT_PASSWORD:
    RABBIT_EXCHANGE: elkexchange
    RABBIT_QUEUE: elkqueue
    RABBIT_SSL_ENABLED: 0 # can be 0, 1, true, false
