"""added dataobject table

Revision ID: bebf004b2b35
Create Date: 2023-09-21 10:06:15.090805

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bebf004b2b35"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_object",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=46), nullable=False),
        sa.Column("path", sa.String(length=100), nullable=False),
        sa.Column(
            "object_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    with op.batch_alter_table("data_object", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_data_object_path"), ["path"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_object", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_object_path"))

    op.drop_table("data_object")
    # ### end Alembic commands ###
