name: MyPy

on:
  push:
  workflow_dispatch:

env:
  PROJECT: seadata

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: rapydo/actions/mypy@v2
        with:
          project: ${PROJECT}
          # install: ...
          ignore: b2handle glom gdapi irods irods.exception tests websocket
